//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1988089
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int ID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
